---
- include_tasks: setup-RedHat.yml
  when: ( ansible_os_family == 'RedHat' or ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "yum" )

- include_tasks: setup-Debian.yml
  when: (ansible_distribution == "Debian")

#- include_tasks: setup-Ubuntu.yml
#  when: (ansible_distribution == "Ubuntu")
